
Showing logs for build [32mablazleon-jxpy-pr-19-pr-build-257c7-1[0m stage [32mfrom-build-pack[0m and container [32mstep-credential-initializer-jl4sg[0m
{"level":"info","ts":1593186736.1337352,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/0.8.0-ns-support: no such file or directory"}
{"level":"info","ts":1593186736.1342132,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mablazleon-jxpy-pr-19-pr-build-257c7-1[0m stage [32mfrom-build-pack[0m and container [32mstep-working-dir-initializer-2n8mp[0m
{"level":"info","ts":1593186737.7421293,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1593186737.744871,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mablazleon-jxpy-pr-19-pr-build-257c7-1[0m stage [32mfrom-build-pack[0m and container [32mstep-place-tools[0m

Showing logs for build [32mablazleon-jxpy-pr-19-pr-build-257c7-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-ablazleon-jxpy-pr-19-pr-build-257c7-h7z4r[0m
{"level":"info","ts":1593186745.0343,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/0.8.0-ns-support: no such file or directory"}
{"level":"info","ts":1593186746.414693,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/*********/**py.git @ master in path /workspace/source"}

Showing logs for build [32mablazleon-jxpy-pr-19-pr-build-257c7-1[0m stage [32mfrom-build-pack[0m and container [32mstep-setup-builder-home[0m

Showing logs for build [32mablazleon-jxpy-pr-19-pr-build-257c7-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:f915d9a0c2fe762803d5f35180ba4d22360b0cb7,19:e091238bf42e40c05dab3a9f19663a7c95e0268f
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git fetch origin --unshallow e091238bf42e40c05dab3a9f19663a7c95e0268f: f915d9a0c2fe762803d5f35180ba4d22360b0cb7:
DEBUG: ran git fetch --unshallow origin e091238bf42e40c05dab3a9f19663a7c95e0268f: f915d9a0c2fe762803d5f35180ba4d22360b0cb7: in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git branch
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git checkout master
DEBUG: ran git checkout master in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git reset --hard f915d9a0c2fe762803d5f35180ba4d22360b0cb7
DEBUG: ran git reset --hard f915d9a0c2fe762803d5f35180ba4d22360b0cb7 in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git clean -fd .
DEBUG: ran clean --force -d . in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git merge e091238bf42e40c05dab3a9f19663a7c95e0268f
DEBUG: ran git merge e091238bf42e40c05dab3a9f19663a7c95e0268f in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git log --format=%H%x1f%an%x1f%ae%x1f%cn%x1f%ce%x1f%s%n%b%x1e f915d9a0c2fe762803d5f35180ba4d22360b0cb7..HEAD
Merged SHA e091238bf42e40c05dab3a9f19663a7c95e0268f with commit message 'Update jenkins-x.yml' into base branch master

Showing logs for build [32mablazleon-jxpy-pr-19-pr-build-257c7-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-python-unittest[0m

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Showing logs for build [32mablazleon-jxpy-pr-19-pr-build-257c7-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
E0626 15:52:31.218678      10 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
[36mINFO[0m[0001] Using dockerignore file: /workspace/source/.dockerignore 
[36mINFO[0m[0001] Retrieving image manifest python:onbuild     
E0626 15:52:31.606904      10 metadata.go:154] while reading 'google-dockercfg' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg
E0626 15:52:31.610063      10 metadata.go:166] while reading 'google-dockercfg-url' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg-url
[36mINFO[0m[0002] Retrieving image manifest python:onbuild     
[36mINFO[0m[0003] Built cross stage deps: map[]                
[36mINFO[0m[0003] Retrieving image manifest python:onbuild     
[36mINFO[0m[0004] Retrieving image manifest python:onbuild     
[36mINFO[0m[0005] Executing 3 build triggers                   
[36mINFO[0m[0005] Checking for cached layer gcr.io/envjenkinsk8udacitycapstone/cache:16e5d4381a19bb1839ed70d19ca4239f2c7c99129be32d7dfc4394b4a89aebcc... 
[36mINFO[0m[0006] Using caching version of cmd: COPY requirements.txt /usr/src/app/ 
[36mINFO[0m[0006] Checking for cached layer gcr.io/envjenkinsk8udacitycapstone/cache:4922f0adc29feba7adbd5468a475b3c1dbe2e93cf37f5068b629b9d7ce5cc7cf... 
[36mINFO[0m[0006] No cached layer found for cmd RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0006] cmd: EXPOSE                                  
[36mINFO[0m[0006] Adding exposed port: 8080/tcp                
[36mINFO[0m[0006] Unpacking rootfs as cmd RUN pip install --no-cache-dir -r requirements.txt requires it. 
[36mINFO[0m[0024] COPY requirements.txt /usr/src/app/          
[36mINFO[0m[0024] Found cached layer, extracting to filesystem 
[36mINFO[0m[0024] RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0024] Taking snapshot of full filesystem...        
[36mINFO[0m[0028] Resolving 27638 paths                        
[36mINFO[0m[0032] cmd: /bin/sh                                 
[36mINFO[0m[0032] args: [-c pip install --no-cache-dir -r requirements.txt] 
[36mINFO[0m[0032] Running: [/bin/sh -c pip install --no-cache-dir -r requirements.txt] 
Collecting pylint==pylint==2.5.3 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement pylint==pylint==2.5.3 (from -r requirements.txt (line 1)) (from versions: 0.15.2, 0.16.0, 0.18.0, 0.18.1, 0.19.0, 0.20.0, 0.21.0, 0.21.1, 0.21.2, 0.21.3, 0.22.0, 0.23.0, 0.24.0, 0.25.0, 0.25.1, 0.25.2, 0.26.0, 0.27.0, 0.28.0, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 2.0.0.dev0, 2.0.0.dev1, 2.0.0.dev2, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0.dev0, 2.3.0.dev1, 2.3.0.dev2, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.5.3)
No matching distribution found for pylint==pylint==2.5.3 (from -r requirements.txt (line 1))
You are using pip version 10.0.1, however version 20.2b1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1
[31m
Pipeline failed on stage 'from-build-pack' : container 'step-build-container-build'. The execution of the pipeline has stopped.[0m
